Update
The changelog, as always:

- New rules: ICMP type whitelisting with stateful checks, rate-limits per each state (and per each source IP address); TTL filtering (beta); fragmented packets dropping; TCP SYN and state != NEW -> DROP; anti-spoofing rule with strict source IP and interface check (if the source IP is like "purely" loopback but we've received something from it not on a loopback interface, then it'll be dropped).
- RST without ACK is rarely valid, let's say, so it isn't allowed by default anymore. Only RST+ACK is allowed & under a rate limit.
- Logging has been added and enabled by default. It is rate-limited to 13 messages per each rule per minute so your logs won't get DDoSed ;)
- Connections rate-limit was fixed: it's 5 connections per second now.  (It was higher than the total connection limit so it wasn't working)
- The tcp_mtu_probing setting is now set to 0 (zero) (disabled) for security.
- Now the script doesn't import the config file when it's not needed.
- Major fixes in the script logic after hours of debugging and thinking.
- Now our custom chain has optimal priority for more efficient filtering.
- We do MSS checking in only one rule instead of two.
- Other minor optimizations.
- Slightly improved the "design" inside the script.
- Many typos were fixed.
- Rule against UDP AMP attacks was removed because it was eating CPU time for almost nothing. (it was useless, in other words)
- And more changes...

Signed-off-by: yuki <92524570+yuk1c@users.noreply.github.com>

diff --git a/antiddos-yuki b/antiddos-yuki
--- a/antiddos-yuki
+++ b/antiddos-yuki
@@ -7,10 +7,8 @@
 # Check where's the script located.
 script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
-# Execute the contents of the config/functions files in the current contxt.
-# It's needed for the script to work properly.
-source "$script_dir/config.sh"           # Import config.sh
-source "$script_dir/functions.sh"        # Import functions.sh
+# Import the functions file.
+source "$script_dir/functions.sh"
 
 # ----------------------------------
 # Call the accidental start prevention function.
@@ -149,7 +147,7 @@ if [ "$SKIP_UPDATE_CHECK" != "true" ]; then
                 ;;
 
             [nN])
-                print_default "You chose not to upgrade. You can skip the update check with the '--skip-update-check' argument."
+                print_default "You chose not to update. This isn't really recommended, so we exit, but there is a --skip-update-check' argument to override this."
                 exit 1
                 ;;
             *)
@@ -162,18 +160,22 @@ fi
 
 # --------------------------------
 
-# Flush all rules and add the 'filter' table.
- "$nft" flush ruleset
- "$nft" add table yuki-script > /dev/null 2>&1
- "$nft" 'add chain ip yuki-script prerouting { type filter hook prerouting priority 0; policy drop; }'
+# Connect the config file.
+source "$script_dir/config.sh"
 
-# Allow the local interface.
+# Flush all rules and add the 'yuki-script' table.
+ "$nft" flush ruleset
+ "$nft" add table yuki-script
+ "$nft" add chain ip yuki-script prerouting '{ type filter hook prerouting priority -200; policy drop; }'
+
+# Allow the local interface and prevent spoofing at the same time.
  "$nft" add rule ip yuki-script prerouting iif "lo" ip saddr 127.0.0.0/8 accept
+ "$nft" add rule ip yuki-script prerouting ip saddr '{ 127.0.0.0/8, 0.0.0.0/8 }' iif != "lo" log prefix \"[yuki-script] Possible Spoofing: \" level debug limit rate 13/minute counter drop
 
 # Allow established and related connections.
  "$nft" add rule ip yuki-script prerouting ct state established,related counter accept
 
-# Allow SSH. You can implement whitelisting here. Below is an example.
+# Allow SSH. You can implement whitelisting here. There's a template below.
 # "$nft" add rule ip yuki-script prerouting ip saddr 192.168.1.0/24 tcp dport "$SSH" accept
  "$nft" add rule ip yuki-script prerouting tcp dport "$SSH" counter accept
 
@@ -185,63 +187,63 @@ fi
 # Basic ruleset.
 
 # Combat some TCP flood attacks by applying rate-limits.
-# ----------------------------------------------------------------
- "$nft" add rule ip yuki-script prerouting ip protocol tcp tcp flags syn limit rate over "$SPL" counter drop
- "$nft" add rule ip yuki-script prerouting ip protocol tcp tcp flags syn,ack limit rate over "$SAPL" counter drop
- "$nft" add rule ip yuki-script prerouting ip protocol tcp tcp flags rst limit rate over "$RPL" counter drop
+# ================================================================
+ "$nft" add rule ip yuki-script prerouting ip protocol tcp tcp flags syn limit rate over "$SPL" log prefix \"[yuki-script] Possible SYN Flood: \" level debug limit rate 13/minute counter drop
+ "$nft" add rule ip yuki-script prerouting ip protocol tcp tcp flags syn,ack limit rate over "$SAPL" log prefix \"[yuki-script] Possible SYN-ACK Flood: \" level debug limit rate 13/minute counter drop
+ "$nft" add rule ip yuki-script prerouting ip protocol tcp tcp flags rst,ack limit rate over "$RPL" log prefix \"[yuki-script] Possible RST-ACK Flood: \" level debug limit rate 13/minute counter drop
 
 # Allow only legitimate TCP flags and flags combinations.
-# ----------------------------------------------------------------
+# ================================================================
  "$nft" add rule ip yuki-script prerouting ip protocol tcp tcp flags ack counter accept
  "$nft" add rule ip yuki-script prerouting ip protocol tcp tcp flags fin,ack counter accept
- "$nft" add rule ip yuki-script prerouting ip protocol tcp tcp flags rst,ack counter accept
  "$nft" add rule ip yuki-script prerouting ip protocol tcp tcp flags psh,ack counter accept
  "$nft" add rule ip yuki-script prerouting ip protocol tcp tcp flags urg,ack counter accept
 
 # Mitigate UDP Floods with a ratelimit.
-# ----------------------------------------------------------------
- "$nft" 'add rule ip yuki-script prerouting ip protocol udp meter udp-flood-limit { ip saddr limit rate over 3000/second } counter drop'
+# ================================================================
+ "$nft" add rule ip yuki-script prerouting ip protocol udp meter udp-flood-limit '{ ip saddr limit rate over 3200/second }' log prefix \"[yuki-script] Possible UDP Flood: \" level debug limit rate 13/minute counter drop
 
-# Mitigate ICMP Floods with a ratelimit. Also, block some ICMP types for enhanced security.
-# ----------------------------------------------------------------
- "$nft" 'add rule ip yuki-script prerouting ip protocol icmp meter icmp-limit { ip saddr limit rate over '"$IPL"' } counter drop'
- "$nft" 'add rule ip yuki-script prerouting icmp type address-mask-request counter drop'
- "$nft" 'add rule ip yuki-script prerouting icmp type router-solicitation counter drop'
- "$nft" 'add rule ip yuki-script prerouting icmp type timestamp-request counter drop'
- "$nft" 'add rule ip yuki-script prerouting icmp type redirect counter drop'
-
-# Safeguard against CPU overload during amplificated DDoS attacks by limiting DNS/NTP packets per second rate (PPS).
-# ----------------------------------------------------------------
- "$nft" 'add rule ip yuki-script prerouting ip protocol udp udp sport { 19,53,123,5353 } meter Amplification-Limit { ip saddr . udp sport timeout 60s limit rate over 256/minute } counter drop'
+# ICMP type whitelisting with state tracking and rate-limiting.
+# ================================================================
+ "$nft" add rule ip yuki-script prerouting icmp type echo-request limit rate 2/second ct state new counter accept # State: New
+ "$nft" add rule ip yuki-script prerouting icmp type parameter-problem limit rate 15/minute ct state related counter accept # State: Related
+ "$nft" add rule ip yuki-script prerouting icmp type '{ echo-reply, timestamp-reply, address-mask-reply }' limit rate 15/minute ct state established counter accept # State: Established
+ "$nft" add rule ip yuki-script prerouting icmp type '{ destination-unreachable, time-exceeded }' limit rate 2/second ct state related,established counter accept # State: Related, Established
 
 # Drop SYN packets with source-port <1024 to prevent some attacks.
-# ----------------------------------------------------------------
- "$nft" 'add rule ip yuki-script prerouting tcp sport != 1024-65535 tcp flags syn / fin,syn,rst,ack counter drop'
+# ================================================================
+ "$nft" add rule ip yuki-script prerouting tcp sport != 1024-65535 tcp flags syn / fin,syn,rst,ack log prefix \"[yuki-script] Invalid TCP SYN Source port: \" level debug limit rate 13/minute counter drop
 
 # Drop all packets with bad states.
-# ----------------------------------------------------------------
- "$nft" 'add rule ip yuki-script prerouting ct state invalid,untracked counter drop'
+# ================================================================
+ "$nft" add rule ip yuki-script prerouting ct state invalid,untracked log prefix \"[yuki-script] Bad packet state: \" level debug limit rate 13/minute counter drop
 
 # Limit connection establishing rate and total connections per each IP address to mitigate attacks like "Socket/Handshake/Slowloris".
- "$nft" add rule ip yuki-script prerouting ip protocol tcp ct state new limit rate 100/second counter drop
- "$nft" 'add set ip yuki-script connlimit0 { type ipv4_addr; flags dynamic; }'
- "$nft" 'add rule ip yuki-script prerouting ip protocol tcp add @connlimit0 { ip saddr ct count over 50 } counter drop'
+# ================================================================
+ "$nft" add rule ip yuki-script prerouting ip protocol tcp ct state new limit rate 5/second log prefix \"[yuki-script] Connection rate-limit triggered: \" level debug limit rate 13/minute counter drop
+ "$nft" add set ip yuki-script connlimit0 '{ type ipv4_addr; flags dynamic; }'
+ "$nft" add rule ip yuki-script prerouting ip protocol tcp add @connlimit0 '{ ip saddr ct count over 16 }' log prefix \"[yuki-script] Connection limit triggered: \" level debug limit rate 13/minute counter drop
 
-# Perform stateful checking to drop packets with CT state NEW but not SYN.
-# This check is a bit heavy, if you have problems with CPU usage, try to remove this rule.
-# ----------------------------------------------------------------
- "$nft" add rule ip yuki-script prerouting ip protocol tcp tcp flags ! syn ct state new counter drop
+# Stateful TCP filtering.
+# ================================================================
+ "$nft" add rule ip yuki-script prerouting ip protocol tcp tcp flags ! syn ct state new log prefix \"[yuki-script] TCP != SYN but state NEW: \" level debug limit rate 13/minute counter drop
+ "$nft" add rule ip yuki-script prerouting ip protocol tcp tcp flags syn ct state ! new log prefix \"[yuki-script] TCP SYN but state != NEW: \" level debug limit rate 13/minute counter drop
 
-# Perform MSS checking for each TCP packet. Drop, if MSS is higher than 1460 bytes or less than 536.
-# You might need to adjust these rules. Also, if you don't use Jumbo Frames, you can set the maximum MSS to 1460.
-# only for a interface
-# ----------------------------------------------------------------
- "$nft" 'add rule ip yuki-script prerouting ip protocol tcp tcp option maxseg size > 8946 counter drop'
- "$nft" 'add rule ip yuki-script prerouting ip protocol tcp tcp option maxseg size < 536 counter drop'
+# Perform MSS checking for each TCP packet.
+# ================================================================
+ "$nft" add rule ip yuki-script prerouting ip protocol tcp tcp option maxseg size != 536-1460 log prefix \"[yuki-script] Invalid MSS value: \" level debug limit rate 13/minute counter drop
+
+# Drop packets with weird TTL values. [beta]
+# ================================================================
+ "$nft" add rule ip yuki-script prerouting ip ttl != 1-128 log prefix \"[yuki-script] Invalid TTL: \" level debug limit rate 13/minute counter drop
+
+# Drop fragmented packets.
+# ================================================================
+ "$nft" add rule ip yuki-script prerouting ip frag-off '& 0x1fff' != 0 log prefix \"[yuki-script] Fragmented packet dropped: \" level debug limit rate 13/minute counter drop
 
 # Advanced ruleset.
 # Not recommended to use until it's fully converted to nftables.
-# ----------------------------------------------------------------
+# ================================================================
 
 #################
 # Generic rules #
@@ -452,25 +454,16 @@ fi
 
 # --------------------------------
 
-###############
-#   Logging   #
-###############
-
-# If you want to enable logging to dmesg, uncomment the following first rule:
-
-# [WASN'T TESTED]
-# The rule below enables logging with the limit of 5 messages per second:
-# "$IP" -A INPUT -m limit --limit 5/m -j LOG --log-prefix "[yuki-script] DROP:" --log-ip-options --log-tcp-options --log-tcp-sequence
-
 # The rules below actually drop packets:
- "$nft" add rule ip yuki-script prerouting counter drop
- "$nft" add rule ip yuki-script prerouting ip protocol tcp counter drop
+ "$nft" add rule ip yuki-script prerouting log prefix \"[yuki-script] Dropped by the generic drop rule: \" level debug limit rate 13/minute counter drop
+ "$nft" add rule ip yuki-script prerouting ip protocol tcp log prefix \"[yuki-script] Dropped by the generic TCP drop rule: \" level debug limit rate 13/minute counter drop
 
 # Sysctl.conf tweaks.
 # --------------------------------
 
 # Backup management.
-# Note: the backups are located in /etc/sysctl_backups/.
+# Note: the backups are located in /etc/sysctl_backups.
+# After you uninstall the script, they aren't deleted and are still kept there.
 
 # If the backup directory does not exist, create it.
 # If cannot create it - show aa error and exit.
@@ -507,44 +500,44 @@ echo -e "
 # Reverse-Path filtering, aka Spoof protection.
 # 0 = Disabled, 1 = Strict, 2 = Loose
 # You need to comment these parameters if you're using an asymmetric routing.
-# ----------------------------------------------------------------
+# ================================================================
  net.ipv4.conf.default.rp_filter = 1    # For all new interfaces
  net.ipv4.conf.all.rp_filter = 1        # For all current interfaces
 
 # Always-on syncookies.
 # You don't need this (!) unless you're being fried by a SYN Flood.
-# ----------------------------------------------------------------
+# ================================================================
 # net.ipv4.tcp_syncookies = 2
 
 # Do less SYN/SYN-ACK retries.
 # If you like to do experiments, you can try to set 1/1.
-# ----------------------------------------------------------------
+# ================================================================
  net.ipv4.tcp_synack_retries = 2
  net.ipv4.tcp_syn_retries = 2
 
 # Don't accept new connections if the TCP backlog is full.
 # Lowers the CPU load if someone is attacking your server and bypassing the rules.
-# ----------------------------------------------------------------
+# ================================================================
  net.ipv4.tcp_abort_on_overflow = 1
 
 # Increase the limit of established connections.
 # High values aren't really good, BTW.
-# ----------------------------------------------------------------
+# ================================================================
  net.core.somaxconn = 8192
 
 # Make your [TCP] network stack compliant with RFC 1337.
 # Slightly improves stability and security.
-# ----------------------------------------------------------------
+# ================================================================
  net.ipv4.tcp_rfc1337 = 1
 
 # Other tweaks.
-# ----------------------------------------------------------------
+# ================================================================
  net.netfilter.nf_conntrack_tcp_loose = 0               # Turn on strict TCP mode for conntrack.
  net.netfilter.nf_conntrack_tcp_ignore_invalid_rst = 1  # Ignore invalid RST packets.
- net.netfilter.nf_conntrack_checksum = 0                # Don't perform checksum calculations by NF.
- net.ipv4.tcp_mtu_probing = 2                           # Always use TCP MTU Probing (Good for bandwidth in some cases).
+ net.netfilter.nf_conntrack_checksum = 0                # Don't perform checksum calculations by NF. Your server's NIC is probably already doing that.
+ net.ipv4.tcp_mtu_probing = 0                           # Do not use TCP MTU probing for additional security & lower CPU load. (it might not be 'the best' for overall performance. You can try these: 1 = TCP MTU Probing when an ICMP BlackHole detected, 2 = Always-on TCP MTU Probing)
  kernel.unprivileged_userns_clone = 0                   # Don't allow unprivileged user namespaces.
- net.ipv4.tcp_thin_linear_timeouts = 1                  # Enable dynamic triggering of thin linear timeouts (for lower retrans latencies)
+ net.ipv4.tcp_thin_linear_timeouts = 1                  # Enable dynamic triggering of thin linear timeouts (for lower TCP retransmission latencies)
  net.ipv4.conf.all.ignore_routes_with_linkdown = 1      # Ignore [IPv4] routes via interfaces that are down. Good for additional reliability.
  net.ipv6.conf.all.ignore_routes_with_linkdown = 1      # Ignore [IPv6] routes via interfaces that are down. Good for additional reliability.
  net.ipv4.ip_local_port_range = 1024 65535              # Increase the range of source ports for less possible port conflicts.
@@ -554,30 +547,28 @@ echo -e "
  net.ipv4.conf.all.drop_unicast_in_l2_multicast = 1     # Drop IPv4 unicast packets encapsulated in link-layer multicast/broadcast frames.
  net.ipv6.conf.all.drop_unicast_in_l2_multicast = 1     # Drop IPv6 unicast packets encapsulated in link-layer multicast/broadcast frames.
  net.ipv4.conf.all.arp_filter = 1                       # ARP Protection (filter).
- net.ipv4.conf.all_arp_ignore = 1                       # Reply to an ARP request only if the target IP address is local address configured on the incoming interface.
+ net.ipv4.conf.all.arp_ignore = 1                       # Reply to an ARP request only if the target IP address is local address configured on the incoming interface.
  net.ipv4.tcp_shrink_window = 1                         # Shrink TCP RWIN when it's necessary. Good for stability and performance.
  net.ipv4.tcp_tw_reuse = 1                              # Reuse TIME_WAIT sockets for new TCP connections. Good for performance.
  net.ipv6.icmp.echo_ignore_multicast = 1                # Ignore ICMPv6 multicast echos.
  net.ipv6.conf.all.drop_unsolicited_na = 1              # Your server received a NA packet but hasn't asked for it with a NS packet? Drop it.
 
 # Exclusive tweaks.
-# ----------------------------------------------------------------
+# ================================================================
  kernel.io_delay_type = 0           # On newer systems, I/O delay is useless, so we can turn it off.
- kernel.nmi_watchdog = 0            # Turn off NMI watchdog, if not needed.
  vm.memfd_noexec = 1                # Don't allow execution of memory-backed files created with 'memfd_create()' (for security).
  vm.numa_stat = 0                   # Turn off NUMA statistics.
+ #kernel.soft_watchdog = 0           # Turn off kernel soft-lockup detector. (for very slight performance gain)
 " > /etc/sysctl.conf
 
-echo "flush ruleset" > /etc/nftables.conf > /dev/null 2>&1
-"$nft" -o list ruleset >> /etc/nftables.conf > /dev/null 2>&1 &
-systemctl enable nftables > /dev/null 2>&1 &
-"$sc_reload" > /dev/null 2>&1 &
+echo "flush ruleset" > /etc/nftables.conf
+"$nft" -o list ruleset > /etc/nftables.conf
+systemctl enable --now nftables > /dev/null &
+eval "$sc_reload" > /dev/null || { print_error "Cannot apply the sysctl.conf tweaks using the '"$sc_reload"' command."; exit 1; } &
 
-clear; print_warning "This is a beta version!"
 print_success "All changes were applied and rules will persist across reboots."
-print_default2 "\nMake sure your network works okay. For example, ping something, do 'sudo apt update', and open another SSH session (if applicable)."
+print_default2 "\nMake sure your network works properly. For example, ping something, do 'sudo apt update', and open another SSH session (if applicable)."
 print_default2 "If you have some problems = sudo systemctl disable nftables, and restart the server."
-print_default2 "\nThere's a guide in the script' readme on how to allow specific ports and more cool stuff, take a look."
+print_default2 "\nThere is a guide in the script's readme on how to allow specific ports and more cool stuff, take a look."
 
-tput sgr0 # Reset terminal color. We use this to prevent the terminal from being colored after the script exits.
-exit 0 # Exit.
+tput sgr0 && exit 0 # Reset the terminal color and exit.
